# Generated by Django 4.0.2 on 2022-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingoroom',
            name='total_players',
        ),
    ]
